sudo: false

language: node_js

node_js:
  - '6'

# Make chrome browser available for testing
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

branches:
  only:
    - master
  before_script:
    - npm install -g surge
    - npm run lint
    - npm test
#    - SL=true npm test
#    - ./node_modules/coveralls/bin/coveralls.js < ./coverage/lcov.info

script:
  - npm run build
  - gzip -k build/index.html
  - npm run bundlesize

after_success:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
    surge ./build -d https://sound-place-prs.surge.sh &&
    node ./node_modules/lighthouse-ci/runlighthouse.js https://sound-place-prs.surge.sh --runner=chrome --score=90; fi'

  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
    surge ./build -d https://sound-place.surge.sh; fi'

install:
  - npm install

cache:
  directories:
    - node_modules

# Necessary to compile native modules for io.js v3 or Node.js v4
env:
  - CXX=g++-4.8

# Necessary to compile native modules for io.js v3 or Node.js v4
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
