language: node_js

node_js:
  - 8.9.0

addons:
  - google-chrome-stable

# Make chrome browser available for testing
before_install:
  - export CHROME_BIN=chromium-browser
  - google-chrome-stable --headless --no-sandbox --remote-debugging-port=9222 http://localhost:80

install:
    - yarn global add lighthouse
    - yarn global add lighthouse-badges
    - yarn global add gh-pages
    - yarn

branches:
  only:
    - master
    - /^greenkeeper/.*$/
  before_script:
    # - yarn lint

script:
  - yarn build

after_success:
  - yarn bundlesize
  - git stash
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./scripts/run_pr_tests; fi'

deploy:
  provider: script
  skip_cleanup: true
  script: bash ./scripts/run_on_deploy.sh
  on:
    branch: master

cache:
  yarn: true
  directories:
    - node_modules
