sudo: false

language: node_js

node_js:
  - '6'

# Make chrome browser available for testing
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

branches:
  only:
    - master
  before_script:
    - npm run lint
    - npm test
#    - SL=true npm test
    - npm build
#    - ./node_modules/coveralls/bin/coveralls.js < ./coverage/lcov.info

after_success:
  - 'echo after_success call $TRAVIS_PULL_REQUEST'
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
    ./node_modules/surge/lib/cli.js ./build -d https://sound-place-$TRAVIS_PULL_REQUEST.surge.sh &&
    ./lighthouse-ci/runlighthouse.js https://sound-place-$TRAVIS_PULL_REQUEST.surge.sh; fi'

  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
    ./node_modules/surge/lib/cli.js ./build -d https://sound-place.surge.sh &&
    ./lighthouse-ci/runlighthouse.js https://sound-place.surge.sh; fi'


install:
  - npm install

cache:
  directories:
    - node_modules

# Necessary to compile native modules for io.js v3 or Node.js v4
env:
  - CXX=g++-4.8

# Necessary to compile native modules for io.js v3 or Node.js v4
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
