language: node_js

node_js:
  - 8.9.0

addons:
  - google-chrome-stable

before_install:
  - export CHROME_PATH="$(which google-chrome-stable)"

install:
    - yarn global add lighthouse
    - yarn global add lighthouse-badges
    - yarn global add gh-pages
    - yarn

branches:
  only:
    - master
    - /^greenkeeper/.*$/
  before_script:
    # - yarn lint

script:
  - yarn build

after_success:
  - yarn bundlesize
  - git stash
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./scripts/run_pr_tests; fi'

deploy:
  provider: script
  skip_cleanup: true
  script: bash ./scripts/run_on_deploy.sh
  on:
    branch: master

cache:
  yarn: true
  directories:
    - node_modules
