sudo: false

language: node_js

node_js:
  - '6'

# Make chrome browser available for testing
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

branches:
  only:
    - master
    - /^greenkeeper/.*$/
  before_script:
    - npm install -g now
    - npm install -g gh-pages
    - npm run lint
    - npm test
#    - SL=true npm test
#    - ./node_modules/coveralls/bin/coveralls.js < ./coverage/lcov.info

script:
  - npm run build
  - npm run bundlesize

after_success:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
    now switch soundplace --token $NOW_TOKEN &&
    URL=$(now ./build -n prs-soundplace --token $NOW_TOKEN --static --public -f) &&
    echo Running lighthouse tests on: $URL &&
    node ./node_modules/lighthouse-ci/runlighthouse.js $URL --runner=chrome --score=100; fi'

  - if [ "$TRAVIS_BRANCH" = "master" ]; then \
    gh-pages -d build; && \
    echo Purging Cloudflare cache... && \
    curl -X DELETE "https://api.cloudflare.com/client/v4/zones/eba0370f80f740b516c1f1ea9612940d/purge_cache" \
        -H "X-Auth-Email: tsirlucas@gmail.com" \
        -H "X-Auth-Key: 2be67ed35ae20b0b84d6460c8cdfdaa70f7f3" \
        -H "Content-Type: application/json" \
        --data '{"purge_everything":true}' && \
        echo Cache purged! fi

install:
  - npm install

cache:
  directories:
    - node_modules

# Necessary to compile native modules for io.js v3 or Node.js v4
env:
  - CXX=g++-4.8

# Necessary to compile native modules for io.js v3 or Node.js v4
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
